export const TEST_CC = 'testCC'
export const DELETE_POST = 'DELETE_POST'
export const NEW_POST = 'NEW_POST'
export const EDIT_POST = 'EDIT_POST'
export const GET_POST = 'GET_POST'
export const NEW_USER = 'NEW_USER'
export const EDIT_USER = 'EDIT_USER'